# Generated by Django 3.0.8 on 2020-11-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default='uncategorized', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='date_bid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
