# Generated by Django 3.0.8 on 2020-11-09 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201109_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingComment',
        ),
    ]
