# Generated by Django 3.0.8 on 2020-11-09 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_delete_listingcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1024, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listing_Comment', to='auctions.Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Listing_Comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bid', to='auctions.Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
