# Generated by Django 3.0.8 on 2021-01-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201110_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_now',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bid_Data', to='auctions.Listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bid_Data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_bid',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/listing/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
